coverage:
  precision: 4
  round: down
  range: 60...100

  status:
    project:
      default:
        enabled: yes
        target: 80%
        threshold: 1%
        if_no_uploads: error

        if_not_found: success
        if_ci_failed: error

    patch:
      default:
        enabled: true
        target: 60%
